import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

// CSS
import "@/styles/globals.css";

// provider
import ClerkAuthenticationProvider from "@/lib/clerk-convex-provider";
import { ThemeProvider } from "@/lib/theme-provider";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
          <ClerkAuthenticationProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </ClerkAuthenticationProvider>
      </body>
    </html>
  );
}
